"""
Django settings for sisedu project.

Generated by 'django-admin startproject' using Django 5.2.11.
"""

import os
from pathlib import Path
from datetime import timedelta

try:
    from dotenv import load_dotenv
except ModuleNotFoundError:
    load_dotenv = None

BASE_DIR = Path(__file__).resolve().parent.parent

# Load backend/.env when available (development convenience)
if load_dotenv is not None:
    load_dotenv(BASE_DIR / ".env")
else:
    env_path = BASE_DIR / ".env"
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#") or "=" not in stripped:
                continue
            key, value = stripped.split("=", 1)
            os.environ.setdefault(key.strip(), value.strip())


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-g3s5by(=h01zyn586t*#=1l-lf9xt=sr9qajj((k3+*(=xy+ns"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

_local_ip = os.getenv("LOCAL_IP", "192.168.0.105").strip()
_default_allowed_hosts = ["localhost", "127.0.0.1", _local_ip]

if DEBUG:
    # In development, allow LAN access through configured local IP.
    allowed_hosts_env = os.getenv("DJANGO_ALLOWED_HOSTS", "")
    ALLOWED_HOSTS = [
        host.strip()
        for host in (allowed_hosts_env.split(",") if allowed_hosts_env else _default_allowed_hosts)
        if host.strip()
    ]
else:
    # In production, require explicit host allow-list.
    ALLOWED_HOSTS = [
        host.strip()
        for host in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")
        if host.strip()
    ]


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "corsheaders",
    "rest_framework",
    "django_filters",
    "rest_framework_simplejwt",

    "banco",
]


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "sisedu.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sisedu.wsgi.application"


# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
LANGUAGE_CODE = "pt-br"
TIME_ZONE = "America/Sao_Paulo"
USE_I18N = True
USE_TZ = True


# Static files
STATIC_URL = "static/"

# Media (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# CORS / CSRF (frontend Vite)
_default_frontend_origins = [
    "http://localhost:5173",
    f"http://{_local_ip}:5173",
]
_default_cors_origins = [
    *_default_frontend_origins,
    "http://127.0.0.1:5173",
]

if DEBUG:
    cors_allowed_origins_env = os.getenv("CORS_ALLOWED_ORIGINS", "")
    CORS_ALLOWED_ORIGINS = [
        origin.strip()
        for origin in (
            cors_allowed_origins_env.split(",") if cors_allowed_origins_env else _default_cors_origins
        )
        if origin.strip()
    ]
else:
    CORS_ALLOWED_ORIGINS = [
        origin.strip()
        for origin in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")
        if origin.strip()
    ]

CORS_ALLOW_CREDENTIALS = True

if DEBUG:
    csrf_trusted_origins_env = os.getenv("CSRF_TRUSTED_ORIGINS", "")
    CSRF_TRUSTED_ORIGINS = [
        origin.strip()
        for origin in (
            csrf_trusted_origins_env.split(",")
            if csrf_trusted_origins_env
            else _default_frontend_origins
        )
        if origin.strip()
    ]
else:
    CSRF_TRUSTED_ORIGINS = [
        origin.strip()
        for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
        if origin.strip()
    ]


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# DRF
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

# JWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# SIGE Acadêmico (cascata escola -> turma -> série)
SIGE_ACADEMICO_BASE_URL = os.getenv(
    "SIGE_ACADEMICO_BASE_URL",
    "",
).strip()
SIGE_ACADEMICO_TOKEN_URL = os.getenv(
    "SIGE_ACADEMICO_TOKEN_URL",
    "",
).strip()
SIGE_ACADEMICO_GRANT_TYPE = os.getenv(
    "SIGE_ACADEMICO_GRANT_TYPE",
    "client_credentials",
).strip()
SIGE_ACADEMICO_CLIENT_ID = os.getenv("SIGE_ACADEMICO_CLIENT_ID", "").strip()
SIGE_ACADEMICO_CLIENT_SECRET = os.getenv("SIGE_ACADEMICO_CLIENT_SECRET", "").strip()
SIGE_ACADEMICO_USERNAME = os.getenv("SIGE_ACADEMICO_USERNAME", "").strip()
SIGE_ACADEMICO_PASSWORD = os.getenv("SIGE_ACADEMICO_PASSWORD", "").strip()
SIGE_ACADEMICO_SCOPE = os.getenv("SIGE_ACADEMICO_SCOPE", "").strip()
SIGE_ACADEMICO_ACCESS_TOKEN = os.getenv("SIGE_ACADEMICO_ACCESS_TOKEN", "").strip()
