# Generated by Django 5.2.11 on 2026-02-19 13:36

import banco.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booklet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.BigIntegerField()),
                ('booklet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banco.booklet')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_ref', models.BigIntegerField()),
                ('student_ref', models.BigIntegerField()),
                ('student_absent', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_by', models.BigIntegerField(blank=True, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banco.offer')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.TextField()),
                ('support_text', models.TextField(null=True)),
                ('support_image', models.FileField(null=True, upload_to=banco.models.rename_upload_question)),
                ('image_reference', models.CharField(max_length=500, null=True)),
                ('command', models.TextField()),
                ('annulled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('descriptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sages', to='banco.descriptor')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='banco.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('option_text', models.TextField(null=True)),
                ('option_image', models.FileField(null=True, upload_to=banco.models.rename_upload_answer)),
                ('correct', models.BooleanField(null=True)),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='banco.questionversion')),
            ],
        ),
        migrations.CreateModel(
            name='BookletItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('booklet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='banco.booklet')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banco.questionversion')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('descriptor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='banco.descriptor')),
            ],
        ),
        migrations.AddField(
            model_name='questionversion',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='banco.skill'),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=1, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='banco.application')),
                ('booklet_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banco.bookletitem')),
            ],
        ),
        migrations.AddField(
            model_name='questionversion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='banco.subject'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='banco.subject')),
            ],
        ),
        migrations.CreateModel(
            name='LegacyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SUBJECT', 'Subject'), ('TOPIC', 'Topic'), ('DESCRIPTOR', 'Descriptor'), ('SKILL', 'Skill')], max_length=20)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True)),
                ('legacy_raw', models.CharField(max_length=400)),
                ('legacy_code', models.CharField(blank=True, default='', max_length=30)),
                ('legacy_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='OK', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('descriptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banco.descriptor')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banco.skill')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banco.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banco.topic')),
            ],
        ),
        migrations.AddField(
            model_name='descriptor',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='banco.topic'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('offer', 'class_ref', 'student_ref'), name='uq_application_unique'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question_version', 'letter'), name='uq_version_letter'),
        ),
        migrations.AddConstraint(
            model_name='bookletitem',
            constraint=models.UniqueConstraint(fields=('booklet', 'order'), name='uq_booklet_order'),
        ),
        migrations.AddConstraint(
            model_name='bookletitem',
            constraint=models.UniqueConstraint(fields=('booklet', 'question_version'), name='uq_booklet_version'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('descriptor', 'code'), name='uq_skill_descriptor_code'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['application'], name='banco_stude_applica_da5133_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['booklet_item'], name='banco_stude_booklet_fda5e2_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['is_correct'], name='banco_stude_is_corr_c6c720_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(fields=('application', 'booklet_item'), name='uq_answer_unique'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.UniqueConstraint(fields=('question', 'version_number'), name='uq_question_version'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('subject', 'description'), name='uq_topic_subject_description'),
        ),
        migrations.AddConstraint(
            model_name='legacymap',
            constraint=models.UniqueConstraint(fields=('type', 'legacy_raw'), name='uq_legacy_type_raw'),
        ),
        migrations.AddConstraint(
            model_name='descriptor',
            constraint=models.UniqueConstraint(fields=('topic', 'code'), name='uq_descriptor_topic_code'),
        ),
    ]
