# Generated by Django 4.2.3 on 2026-02-15 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caderno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('excluido', models.BooleanField(default=False, verbose_name='Excluído?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cadernos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Caderno',
                'verbose_name_plural': 'Cadernos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=5, unique=True)),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=30, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['saber__disciplina__nome', 'saber__codigo', 'codigo', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado_html', models.TextField(verbose_name='Enunciado')),
                ('texto_suporte_html', models.TextField(blank=True, default='', verbose_name='Texto de apoio')),
                ('imagem_suporte', models.ImageField(blank=True, null=True, upload_to='questoes/suporte/', verbose_name='Imagem de apoio')),
                ('ref_imagem', models.CharField(blank=True, default='', max_length=500, verbose_name='Referência da imagem')),
                ('excluida', models.BooleanField(default=False, verbose_name='Excluída')),
                ('is_private', models.BooleanField(default=False, verbose_name='Privada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questoes', to='banco.disciplina', verbose_name='Disciplina')),
                ('habilidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questoes', to='banco.habilidade', verbose_name='Habilidade')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Saber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=20, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saberes', to='banco.disciplina', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Saber',
                'verbose_name_plural': 'Saberes',
                'ordering': ['disciplina__nome', 'codigo', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(verbose_name='Ordem')),
                ('texto_html', models.TextField(blank=True, default='', verbose_name='Texto da alternativa')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='questoes/respostas/', verbose_name='Imagem da alternativa')),
                ('correta', models.BooleanField(default=False, verbose_name='Correta?')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='banco.questao', verbose_name='Questão')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
                'ordering': ['questao_id', 'ordem'],
            },
        ),
        migrations.AddField(
            model_name='questao',
            name='saber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questoes', to='banco.saber', verbose_name='Saber'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem')),
                ('anulada', models.BooleanField(default=False, verbose_name='Anulada?')),
                ('caderno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='banco.caderno', verbose_name='Caderno')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='banco.questao', verbose_name='Questão')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='habilidade',
            name='saber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habilidades', to='banco.saber', verbose_name='Saber'),
        ),
        migrations.AddConstraint(
            model_name='saber',
            constraint=models.UniqueConstraint(fields=('disciplina', 'codigo'), name='uniq_saber_codigo_por_disciplina'),
        ),
        migrations.AddConstraint(
            model_name='resposta',
            constraint=models.UniqueConstraint(fields=('questao', 'ordem'), name='uniq_ordem_por_questao'),
        ),
        migrations.AddConstraint(
            model_name='resposta',
            constraint=models.UniqueConstraint(condition=models.Q(('correta', True)), fields=('questao',), name='uniq_uma_correta_por_questao'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('caderno', 'ordem'), name='uniq_ordem_por_caderno'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('caderno', 'questao'), name='uniq_questao_por_caderno'),
        ),
        migrations.AddConstraint(
            model_name='habilidade',
            constraint=models.UniqueConstraint(fields=('saber', 'codigo'), name='uniq_habilidade_codigo_por_saber'),
        ),
    ]
