# Generated by Django 4.2.3 on 2026-02-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='comando_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
