# Generated by Django 4.2.3 on 2026-02-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_questao_comando_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='comando_html',
            field=models.TextField(verbose_name='Comando'),
        ),
    ]
