# Generated by Django 5.2.11 on 2026-02-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_chatconversation_chatmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatconversation',
            name='current_step',
            field=models.CharField(default='start', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='fallback_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
